
dist: focal

arch:
  - amd64

services:
  - docker

os: linux

language: php

php:
  - 8.1

stages:
  - lint
  - test

env:
  - SDK=Android11Java8
  - SDK=Android11Java11
  - SDK=Android12Java8
  - SDK=Android12Java11
  - SDK=CLINode14
  - SDK=CLINode16
  - SDK=DartBeta
  - SDK=DartStable
  - SDK=Deno1193
  - SDK=Deno1303
  - SDK=FlutterStable
  - SDK=FlutterBeta
  - SDK=Go112
  - SDK=Go118
  - SDK=KotlinJava8
  - SDK=KotlinJava11
  - SDK=KotlinJava17
  - SDK=Node12
  - SDK=Node14
  - SDK=Node16
  - SDK=PHP74
  - SDK=PHP80
  - SDK=Python38
  - SDK=Python39
  - SDK=Python310
  - SDK=Ruby27
  - SDK=Ruby30
  - SDK=Ruby31
  - SDK=AppleSwift55
  - SDK=Swift55
  - SDK=WebChromium
  - SDK=WebNode

notifications:
  email:
    - team@appwrite.io

jobs:
  include:
    - stage: lint
      name: Lint
      install:
        - composer install
      script:
        - composer lint

before_install:
  - >
    if [ ! -z "${DOCKERHUB_PULL_USERNAME:-}" ]; then
      echo "${DOCKERHUB_PULL_PASSWORD}" | docker login --username "${DOCKERHUB_PULL_USERNAME}" --password-stdin
    fi
install:
  - docker --version
  - composer install
script:
  - composer test tests/${SDK}Test.php