[tool.djlint]
profile="jinja"

indent=4
max_line_length=1200
max_blank_lines=1
preserve_blank_lines=true
preserve_leading_space=true

format_js=true
format_css=true

extension="twig"

ignore="H006,H030,H031"

exclude=".git,vendor,tests/sdks,node_modules"

use_gitignore=true
