services:
  mockapi:
    container_name: mockapi
    ports:
      - 3175:80
    build:
      context: .
      args:
        DEBUG: "false"
        TESTING: "true"
        VERSION: "dev"
    entrypoint:
      - php
      - -e
      - app/http.php
    volumes:
      - ./app:/usr/src/code/app
      - ./src:/usr/src/code/src
      - mockapi-cache:/storage/cache
    networks:
      - mockapi

networks:
  mockapi:
    name: mockapi

volumes:
  mockapi-cache:
